run:
  timeout: 10m
  tests: true
  go: "1.22"

output:
  formats:
    - format: colored-tab

  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  sort-order:
    - linter

linters:
  enable-all: true
  disable:
    # deprecated
    - gomnd
    - exportloopref
    - execinquery

    # overkill
    - depguard
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - nlreturn
    - wsl
  fast: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true
