# https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
linters:
  default: all
  disable:
    - depguard
    - dogsled
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godot
    - ireturn
    - lll
    - nlreturn
    - revive
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order:
    - linter
    - severity
    - file
run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  allow-parallel-runners: false
  allow-serial-runners: false
  tests: false
  go: "1.23"
  concurrency: 4
severity:
  default: error
