services:

  prometheus:
    container_name: prometheus
    image:  prom/prometheus
    ports: 
      - 9090:9090
    volumes:
      - ./tools/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./tools/prometheus/webserver.config.yml:/etc/prometheus/webserver.config.yml
      - ./tools/prometheus/webserver.rules.yml:/etc/prometheus/webserver.rules.yml
      - ./tools/prometheus/webserver.test.yml:/etc/prometheus/webserver.test.yml
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --log.level=error
    healthcheck:
      test: promtool check healthy
      start_period: 10s
      start_interval: 1s
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./tools/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./tools/grafana/grafana.db:/var/lib/grafana/grafana.db
    depends_on:
      - prometheus
